image: datamechanics/spark:3.1.1-latest
before_script:
  - apt-get update && apt-get install -y --no-install-recommends unixodbc-dev unixodbc libpq-dev
  - pip install findspark flake8 pytest>=6.1.1 pytest-cov

stages:
  - test

test:
  stage: test
  script:
    - echo "Check Unit Tests"
    - python setup.py install
    - pytest "./tests/unittests/"
  only:
    - merge_requests
  tags:
    - dsi
